
version: 2.1

orbs:
  android: circleci/android@3.1.0

jobs:
  build:
    docker:
      - image: cimg/android:2025.10

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      # Checkout the code as the first step.
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle.kts" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: "Compile multiplatform"
          command: ./gradlew dex -Prapid.append-version=<<pipeline.project.type>>-<<pipeline.git.branch>>-<<pipeline.git.revision>>

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle.kts" }}

      - run:
          name: "Place jars in better location"
          command: |
            mkdir finals
            mv ./core/build/libs/core.jar finals/yellow-java.jar
            mv ./core/build/libs/coreDesktop.jar finals/yellow-java-desktop-only.jar
            mv ./core/build/libs/native-loader.jar finals/
          
      - store_artifacts:
          path: ./finals

      - persist_to_workspace:
          root: ./finals
          paths:
            - yellow-java.jar
            - yellow-java-desktop-only.jar
            - native-loader.jar



  publish:
    docker:
      - image: cibuilds/github:0.10

    steps:
      - attach_workspace:
          at: ./finals

      - run:
          name: "Publish on builds repo"
          command: |
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r yellow-java-builds -c ${CIRCLE_SHA1} -n <<pipeline.project.type>>-<<pipeline.git.branch>>-<<pipeline.git.revision>> -delete ${CIRCLE_BUILD_NUM} ./finals


workflows:
  compile:
    jobs:
      - build
      - publish

