
version: 2.1

orbs:
  android: circleci/android@3.1.0

jobs:
  build:
    docker:
      - image: cimg/android:2025.08

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      # Checkout the code as the first step.
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle.kts" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: ls $ANDROID_HOME/build-tools

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle.kts" }}


workflows:
  compile:
    jobs:
      - build